{% set name = "daltools" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5bd3991e23a9b58ba2d596869c84e41ffac42ebdc42bb34fe8e9f336163743ca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - blocked-matrix-utils
    - fortran-binary
    - numpy
    - python >=3.6

test:
  imports:
    - daltools

about:
  home: https://github.com/vahtras/daltools
  summary: Misc utilities for extracting data from Dalton files
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - robertodr
    - vahtras
