{% set name = "daltools" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4403cc510e56dc097cd01d595d2d301ec9db143fd9a684b56abe7978f25c884

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - blocked-matrix-utils
    - fortran-binary
    - numpy
    - python >=3.6

test:
  imports:
    - daltools

about:
  home: https://github.com/vahtras/daltools
  summary: Misc utilities for extracting data from Dalton files
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - robertodr
    - vahtras
